apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: apache-canary
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deployment  # Refers to the stable Apache deployment
  service:
    port: 80
    primaryService: apache-primary  # The service for the stable version
    canaryService: nginx-canary     # The service for the canary version
  canaryAnalysis:
    interval: 1m              # Perform analysis every 1 minute
    threshold: 5              # Maximum number of checks before declaring failure
    maxWeight: 50             # Maximum 50% of traffic to the canary
    stepWeight: 10            # Traffic increase by 10% at each step
    metrics:
      - name: request-success-rate
        threshold: 99         # Success rate must stay above 99%
      - name: request-duration
        threshold: 500        # Request duration must stay below 500ms
